project_id = "yxyfjewdrzjscgbinudv"

[functions.send-vaccine-reminders]
verify_jwt = false

[functions.send-appointment-confirmations]
verify_jwt = false

[functions.send-appointment-reminders]
verify_jwt = false

[functions.confirm-appointment]
verify_jwt = false

[functions.send-verification-notification]
verify_jwt = false

[functions.send-credit-notification]
verify_jwt = false